name: 'Commit Message Check'
on:
  pull_request:
    branches:
      -main
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Message
        uses: alezhuu/check-message-action@vmain
        with:
          message: ${{ github.event.head_commit.message }}
